import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import { KeyProvider } from "@/lib/KeyContext";

export const metadata: Metadata = {
  title: "KMIP Banking App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <KeyProvider>
          <Header />
          {children}
        </KeyProvider>
      </body>
    </html>
  );
}
